homeassistant:
  automation ui-automation: !include automations.yaml
  automation: !include_dir_list include/automations

  script ui-script: !include scripts.yaml
  script: !include_dir_named include/scripts

  default_config:

  customize: !include include/customize.yaml
  group: !include include/groups.yaml
  #  packages: !include_dir_named include/
  scene: !include include/scenes.yaml

  # *** NOTE: The following 9 lines can be removed by setting these values in the Home Assistant settings at "Configuration > Settings > General".
  name: 007 Home Assistant
  latitude: 43.02232942222318
  longitude: -71.20960235595705
  elevation: 430
  unit_system: imperial
  currency: USD
  time_zone: "America/New_York"
  external_url: "https://007DJ.DuckDNS.org"
  internal_url: "http://homeassistant.local:8123"

  #  allowlist_external_dirs:
  #  allowlist_external_urls:
  #  media_dirs:
  #    media: "/media"
  #    recordings: "/mnt/recordings"

  http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

  # Text to speech
  tts:
    - platform: google_translate

  alexa_media:
    accounts:
      - email: !secret amazon_user
        password: !secret amazon_password
        url: amazon.com

  notify:
    - name: 007DJ-Surveilance
      platform: smtp
      server: mail.myfairpoint.net
      port: 1025
      sender: !secret 007Surveilance_fairpoint_email
      username: !secret 007Surveilance_fairpoint_email
      password: !secret 007Surveilance_fairpoint_password
      recipient: !secret verizon_0415
  #   recipient: roger.j.moore@comcast.net
      sender_name: Home Assistant Automation

  ##Actionable Notifications
  input_text:
    alexa_actionable_notification:
      name: Alexa Actionable Notification Holder
      max: 255
      initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
